!
  Knockout JavaScript library v3.5.0
  (c) The Knockout.js team - httpknockoutjs.com
  License MIT (httpwww.opensource.orglicensesmit-license.php)
 

(function() {(function(p){var z=this(0,eval)(this),w=z.document,R=z.navigator,v=z.jQuery,H=z.JSON;vundefined===typeof jQuery(v=jQuery);(function(p){function===typeof define&&define.amddefine([exports,require],p)object===typeof exports&&object===typeof modulep(module.exportsexports)p(z.ko={})})(function(S,T){function K(a,c){return null===atypeof a in Wa===c!1}function X(b,c){var d;return function(){d(d=a.a.setTimeout(function(){d=p;b()},c))}}function Y(b,c){var d;return function(){clearTimeout(d);
d=a.a.setTimeout(b,c)}}function Z(a,c){c&&change!==cbeforeChange===cthis.oc(a)this.bb(a,c)this.pc(a)}function aa(a,c){null!==c&&c.s&&c.s()}function ba(a,c){var d=this.pd,e=d[t];e.qa(this.Pb&&this.kb[c](d.tc(c,a,this.kb[c]),this.kb[c]=null,--this.Pb)e.F[c]d.tc(c,a,e.G{daa}d.Zc(a)),a.Ka&&a.fd())}var a=undefined!==typeof SS{};a.b=function(b,c){for(var d=b.split(.),e=a,f=0;fd.length-1;f++)e=e[d[f]];e[d[d.length-1]]=c};a.J=function(a,c,d){a[c]=d};a.version=3.5.0;a.b(version,
a.version);a.options={deferUpdates!1,useOnlyNativeEvents!1,foreachHidesDestroyed!1};a.a=function(){function b(a,b){for(var c in a)f.call(a,c)&&b(c,a[c])}function c(a,b){if(b)for(var c in b)f.call(b,c)&&(a[c]=b[c]);return a}function d(a,b){a.__proto__=b;return a}function e(b,c,d,e){var k=b[c].match(n)[];a.a.C(d.match(n),function(b){a.a.Oa(k,b,e)});b[c]=k.join( )}var f=Object.prototype.hasOwnProperty,g={__proto__[]}instanceof Array,h=function===typeof Symbol,m={},l={};m[R&&Firefox2i.test(R.userAgent)
KeyboardEventUIEvents]=[keyup,keydown,keypress];m.MouseEvents=click dblclick mousedown mouseup mousemove mouseover mouseout mouseenter mouseleave.split( );b(m,function(a,b){if(b.length)for(var c=0,d=b.length;cd;c++)l[b[c]]=a});var k={propertychange!0},q=w&&function(){for(var a=3,b=w.createElement(div),c=b.getElementsByTagName(i);b.innerHTML=x3c!--[if gt IE + ++a+]ii![endif]--x3e,c[0];);return 4aap}(),n=S+g,r;return{Ic[authenticity_token,^__RequestVerificationToken(_.)$],
Cfunction(a,b,c){for(var d=0,e=a.length;de;d++)b.call(c,a[d],d,a)},Afunction==typeof Array.prototype.indexOffunction(a,b){return Array.prototype.indexOf.call(a,b)}function(a,b){for(var c=0,d=a.length;cd;c++)if(a[c]===b)return c;return-1},Lbfunction(a,b,c){for(var d=0,e=a.length;de;d++)if(b.call(c,a[d],d,a))return a[d];return p},hbfunction(b,c){var d=a.a.A(b,c);0db.splice(d,1)0===d&&b.shift()},vcfunction(b){var c=[];b&&a.a.C(b,function(b){0a.a.A(c,b)&&c.push(b)});return c},Mbfunction(a,
b,c){var d=[];if(a)for(var e=0,k=a.length;ek;e++)d.push(b.call(c,a[e],e));return d},fbfunction(a,b,c){var d=[];if(a)for(var e=0,k=a.length;ek;e++)b.call(c,a[e],e)&&d.push(a[e]);return d},gbfunction(a,b){if(b instanceof Array)a.push.apply(a,b);else for(var c=0,d=b.length;cd;c++)a.push(b[c]);return a},Oafunction(b,c,d){var e=a.a.A(a.a.$b(b),c);0ed&&b.push(c)db.splice(e,1)},Bag,extendc,setPrototypeOfd,zbgdc,Ob,Hafunction(a,b,c){if(!a)return a;var d={},e;for(e in a)f.call(a,e)&&(d[e]=
b.call(c,a[e],e,a));return d},Sbfunction(b){for(;b.firstChild;)a.removeNode(b.firstChild)},Xbfunction(b){b=a.a.la(b);for(var c=(b[0]&&b[0].ownerDocumentw).createElement(div),d=0,e=b.length;de;d++)c.appendChild(a.na(b[d]));return c},Cafunction(b,c){for(var d=0,e=b.length,k=[];de;d++){var f=b[d].cloneNode(!0);k.push(ca.na(f)f)}return k},uafunction(b,c){a.a.Sb(b);if(c)for(var d=0,e=c.length;de;d++)b.appendChild(c[d])},Wcfunction(b,c){var d=b.nodeType[b]b;if(0d.length){for(var e=d[0],
k=e.parentNode,f=0,l=c.length;fl;f++)k.insertBefore(c[f],e);f=0;for(l=d.length;fl;f++)a.removeNode(d[f])}},Uafunction(a,b){if(a.length){for(b=8===b.nodeType&&b.parentNodeb;a.length&&a[0].parentNode!==b;)a.splice(0,1);for(;1a.length&&a[a.length-1].parentNode!==b;)a.length--;if(1a.length){var c=a[0],d=a[a.length-1];for(a.length=0;c!==d;)a.push(c),c=c.nextSibling;a.push(d)}}return a},Ycfunction(a,b){7qa.setAttribute(selected,b)a.selected=b},Cbfunction(a){return null===aa===pa.trim
a.trim()a.toString().replace(^[sxa0]+[sxa0]+$g,)},Tdfunction(a,b){a=a;return b.lengtha.length!1a.substring(0,b.length)===b},udfunction(a,b){if(a===b)return!0;if(11===a.nodeType)return!1;if(b.contains)return b.contains(1!==a.nodeTypea.parentNodea);if(b.compareDocumentPosition)return 16==(b.compareDocumentPosition(a)&16);for(;a&&a!=b;)a=a.parentNode;return!!a},Rbfunction(b){return a.a.ud(b,b.ownerDocument.documentElement)},jdfunction(b){return!!a.a.Lb(b,a.a.Rb)},Pfunction(a){return a&&
a.tagName&&a.tagName.toLowerCase()},zcfunction(b){return a.onErrorfunction(){try{return b.apply(this,arguments)}catch(c){throw a.onError&&a.onError(c),c;}}b},setTimeoutfunction(b,c){return setTimeout(a.a.zc(b),c)},Fcfunction(b){setTimeout(function(){a.onError&&a.onError(b);throw b;},0)},Hfunction(b,c,d){var e=a.a.zc(d);d=k[c];if(a.options.useOnlyNativeEventsd!v)if(dfunction!=typeof b.addEventListener)if(undefined!=typeof b.attachEvent){var f=function(a){e.call(b,a)},l=on+c;b.attachEvent(l,
f);a.a.I.za(b,function(){b.detachEvent(l,f)})}else throw Error(Browser doesn't support addEventListener or attachEvent);else b.addEventListener(c,e,!1);else r(r=function==typeof v(b).ononbind),v(b)[r](c,e)},Fbfunction(b,c){if(!b!b.nodeType)throw Error(element must be a DOM node when calling triggerEvent);var d;input===a.a.P(b)&&b.type&&click==c.toLowerCase()(d=b.type,d=checkbox==dradio==d)d=!1;if(a.options.useOnlyNativeEvents!vd)if(function==typeof w.createEvent)if(function==
typeof b.dispatchEvent)d=w.createEvent(l[c]HTMLEvents),d.initEvent(c,!0,!0,z,0,0,0,0,0,!1,!1,!1,!1,0,b),b.dispatchEvent(d);else throw Error(The supplied element doesn't support dispatchEvent);else if(d&&b.click)b.click();else if(undefined!=typeof b.fireEvent)b.fireEvent(on+c);else throw Error(Browser doesn't support triggering events);else v(b).trigger(c)},cfunction(b){return a.N(b)b()b},$bfunction(b){return a.N(b)b.w()b},Ebfunction(b,c,d){var k;c&&(object===typeof b.classList
(k=b.classList[daddremove],a.a.C(c.match(n),function(a){k.call(b.classList,a)}))string===typeof b.className.baseVale(b.className,baseVal,c,d)e(b,className,c,d))},Abfunction(b,c){var d=a.a.c(c);if(null===dd===p)d=;var e=a.h.firstChild(b);!e3!=e.nodeTypea.h.nextSibling(e)a.h.ua(b,[b.ownerDocument.createTextNode(d)])e.data=d;a.a.zd(b)},Xcfunction(a,b){a.name=b;if(7=q)try{var c=a.name.replace([&']g,function(a){return&#+a.charCodeAt(0)+;});a.mergeAttributes(w.createElement(input name='+
c+'),!1)}catch(d){}},zdfunction(a){9=q&&(a=1==a.nodeTypeaa.parentNode,a.style&&(a.style.zoom=a.style.zoom))},vdfunction(a){if(q){var b=a.style.width;a.style.width=0;a.style.width=b}},Odfunction(b,c){b=a.a.c(b);c=a.a.c(c);for(var d=[],e=b;e=c;e++)d.push(e);return d},lafunction(a){for(var b=[],c=0,d=a.length;cd;c++)b.push(a[c]);return b},Dafunction(a){return hSymbol(a)a},Xd6===q,Yd7===q,Wq,Kcfunction(b,c){for(var d=a.a.la(b.getElementsByTagName(input)).concat(a.a.la(b.getElementsByTagName(textarea))),
e=string==typeof cfunction(a){return a.name===c}function(a){return c.test(a.name)},k=[],f=d.length-1;0=f;f--)e(d[f])&&k.push(d[f]);return k},Mdfunction(b){returnstring==typeof b&&(b=a.a.Cb(b))H&&H.parseH.parse(b)(new Function(return +b))()null},fcfunction(b,c,d){if(!H!H.stringify)throw Error(Cannot find JSON.stringify(). Some browsers (e.g., IE  8) don't support it natively, but you can overcome this by adding a script reference to json2.js, downloadable from httpwww.json.orgjson2.js);
return H.stringify(a.a.c(b),c,d)},Ndfunction(c,d,e){e=e{};var k=e.params{},f=e.includeFieldsthis.Ic,l=c;if(object==typeof c&&form===a.a.P(c))for(var l=c.action,h=f.length-1;0=h;h--)for(var g=a.a.Kc(c,f[h]),m=g.length-1;0=m;m--)k[g[m].name]=g[m].value;d=a.a.c(d);var n=w.createElement(form);n.style.display=none;n.action=l;n.method=post;for(var q in d)c=w.createElement(input),c.type=hidden,c.name=q,c.value=a.a.fc(a.a.c(d[q])),n.appendChild(c);b(k,function(a,b){var c=w.createElement(input);
c.type=hidden;c.name=a;c.value=b;n.appendChild(c)});w.body.appendChild(n);e.submittere.submitter(n)n.submit();setTimeout(function(){n.parentNode.removeChild(n)},0)}}}();a.b(utils,a.a);a.b(utils.arrayForEach,a.a.C);a.b(utils.arrayFirst,a.a.Lb);a.b(utils.arrayFilter,a.a.fb);a.b(utils.arrayGetDistinctValues,a.a.vc);a.b(utils.arrayIndexOf,a.a.A);a.b(utils.arrayMap,a.a.Mb);a.b(utils.arrayPushAll,a.a.gb);a.b(utils.arrayRemoveItem,a.a.hb);a.b(utils.cloneNodes,a.a.Ca);a.b(utils.createSymbolOrString,
a.a.Da);a.b(utils.extend,a.a.extend);a.b(utils.fieldsIncludedWithJsonPost,a.a.Ic);a.b(utils.getFormFields,a.a.Kc);a.b(utils.objectMap,a.a.Ha);a.b(utils.peekObservable,a.a.$b);a.b(utils.postJson,a.a.Nd);a.b(utils.parseJson,a.a.Md);a.b(utils.registerEventHandler,a.a.H);a.b(utils.stringifyJson,a.a.fc);a.b(utils.range,a.a.Od);a.b(utils.toggleDomNodeCssClass,a.a.Eb);a.b(utils.triggerEvent,a.a.Fb);a.b(utils.unwrapObservable,a.a.c);a.b(utils.objectForEach,a.a.O);a.b(utils.addOrRemoveItem,
a.a.Oa);a.b(utils.setTextContent,a.a.Ab);a.b(unwrap,a.a.c);Function.prototype.bind(Function.prototype.bind=function(a){var c=this;if(1===arguments.length)return function(){return c.apply(a,arguments)};var d=Array.prototype.slice.call(arguments,1);return function(){var e=d.slice(0);e.push.apply(e,arguments);return c.apply(a,e)}});a.a.g=new function(){var b=0,c=__ko__+(new Date).getTime(),d={},e,f;a.a.W(e=function(a,e){var f=a[c];if(!fnull===f!d[f]){if(!e)return p;f=a[c]=ko+b++;d[f]=
{}}return d[f]},f=function(a){var b=a[c];return b(delete d[b],a[c]=null,!0)!1})(e=function(a,b){var d=a[c];!d&&b&&(d=a[c]={});return d},f=function(a){return a[c](delete a[c],!0)!1});return{getfunction(a,b){var c=e(a,!1);return c&&c[b]},setfunction(a,b,c){(a=e(a,c!==p))&&(a[b]=c)},Tbfunction(a,b,c){a=e(a,!0);return a[b](a[b]=c)},clearf,Zfunction(){return b++ +c}}};a.b(utils.domData,a.a.g);a.b(utils.domData.clear,a.a.g.clear);a.a.I=new function(){function b(b,c){var d=a.a.g.get(b,e);
d===p&&c&&(d=[],a.a.g.set(b,e,d));return d}function c(c){var e=b(c,!1);if(e)for(var e=e.slice(0),f=0;fe.length;f++)e[f](c);a.a.g.clear(c);a.a.I.cleanExternalData(c);g[c.nodeType]&&d(c.childNodes,!0)}function d(b,d){for(var e=[],k,f=0;fb.length;f++)if(!d8===b[f].nodeType)if(c(e[e.length]=k=b[f]),b[f]!==k)for(;f--&&-1==a.a.A(e,b[f]););}var e=a.a.g.Z(),f={1!0,8!0,9!0},g={1!0,9!0};return{zafunction(a,c){if(function!=typeof c)throw Error(Callback must be a function);b(a,!0).push(c)},xbfunction(c,
d){var f=b(c,!1);f&&(a.a.hb(f,d),0==f.length&&a.a.g.set(c,e,p))},nafunction(a){f[a.nodeType]&&(c(a),g[a.nodeType]&&d(a.getElementsByTagName()));return a},removeNodefunction(b){a.na(b);b.parentNode&&b.parentNode.removeChild(b)},cleanExternalDatafunction(a){v&&function==typeof v.cleanData&&v.cleanData([a])}}};a.na=a.a.I.na;a.removeNode=a.a.I.removeNode;a.b(cleanNode,a.na);a.b(removeNode,a.removeNode);a.b(utils.domNodeDisposal,a.a.I);a.b(utils.domNodeDisposal.addDisposeCallback,a.a.I.za);
a.b(utils.domNodeDisposal.removeDisposeCallback,a.a.I.xb);(function(){var b=[0,,],c=[1,table,table],d=[3,tabletbodytr,trtbodytable],e=[1,select multiple='multiple',select],f={theadc,tbodyc,tfootc,tr[2,tabletbody,tbodytable],tdd,thd,optione,optgroupe},g=8=a.a.W;a.a.ta=function(c,d){var e;if(v)if(v.parseHTML)e=v.parseHTML(c,d)[];else{if((e=v.clean([c],d))&&e[0]){for(var k=e[0];k.parentNode&&11!==k.parentNode.nodeType;)k=k.parentNode;
k.parentNode&&k.parentNode.removeChild(k)}}else{(e=d)(e=w);var k=e.parentWindowe.defaultViewz,q=a.a.Cb(c).toLowerCase(),n=e.createElement(div),r;r=(q=q.match(^(x3c!--.--x3es)([a-z]+)[s]))&&f[q[1]]b;q=r[0];r=ignoreddiv+r[1]+c+r[2]+div;function==typeof k.innerShivn.appendChild(k.innerShiv(r))(g&&e.body.appendChild(n),n.innerHTML=r,g&&n.parentNode.removeChild(n));for(;q--;)n=n.lastChild;e=a.a.la(n.lastChild.childNodes)}return e};a.a.Ld=function(b,c){var d=a.a.ta(b,
c);return d.length&&d[0].parentElementa.a.Xb(d)};a.a.dc=function(b,c){a.a.Sb(b);c=a.a.c(c);if(null!==c&&c!==p)if(string!=typeof c&&(c=c.toString()),v)v(b).html(c);else for(var d=a.a.ta(c,b.ownerDocument),e=0;ed.length;e++)b.appendChild(d[e])}})();a.b(utils.parseHtmlFragment,a.a.ta);a.b(utils.setHtml,a.a.dc);a.aa=function(){function b(c,e){if(c)if(8==c.nodeType){var f=a.aa.Tc(c.nodeValue);null!=f&&e.push({sdc,Jdf})}else if(1==c.nodeType)for(var f=0,g=c.childNodes,h=g.length;fh;f++)b(g[f],
e)}var c={};return{Wbfunction(a){if(function!=typeof a)throw Error(You can only pass a function to ko.memoization.memoize());var b=(4294967296(1+Math.random())0).toString(16).substring(1)+(4294967296(1+Math.random())0).toString(16).substring(1);c[b]=a;returnx3c!--[ko_memo+b+]--x3e},adfunction(a,b){var f=c[a];if(f===p)throw Error(Couldn't find any memo with ID +a+. Perhaps it's already been unmemoized.);try{return f.apply(null,b[]),!0}finally{delete c[a]}},bdfunction(c,e){var f=
[];b(c,f);for(var g=0,h=f.length;gh;g++){var m=f[g].sd,l=[m];e&&a.a.gb(l,e);a.aa.ad(f[g].Jd,l);m.nodeValue=;m.parentNode&&m.parentNode.removeChild(m)}},Tcfunction(a){return(a=a.match(^[ko_memo(.)]$))a[1]null}}}();a.b(memoization,a.aa);a.b(memoization.memoize,a.aa.Wb);a.b(memoization.unmemoize,a.aa.ad);a.b(memoization.parseMemoText,a.aa.Tc);a.b(memoization.unmemoizeDomNodeAndDescendants,a.aa.bd);a.ma=function(){function b(){if(f)for(var b=f,c=0,d;hf;)if(d=e[h++]){if(hb){if(5E3=
++c){h=f;a.a.Fc(Error('Too much recursion' after processing +c+ task groups.));break}b=f}try{d()}catch(g){a.a.Fc(g)}}}function c(){b();h=f=e.length=0}var d,e=[],f=0,g=1,h=0;z.MutationObserverd=function(a){var b=w.createElement(div);(new MutationObserver(a)).observe(b,{attributes!0});return function(){b.classList.toggle(foo)}}(c)d=w&&onreadystatechangein w.createElement(script)function(a){var b=w.createElement(script);b.onreadystatechange=function(){b.onreadystatechange=null;w.documentElement.removeChild(b);
b=null;a()};w.documentElement.appendChild(b)}function(a){setTimeout(a,0)};return{schedulerd,ybfunction(b){fa.ma.scheduler(c);e[f++]=b;return g++},cancelfunction(a){a=a-(g-f);a=h&&af&&(e[a]=null)},resetForTestingfunction(){var a=f-h;h=f=e.length=0;return a},Rdb}}();a.b(tasks,a.ma);a.b(tasks.schedule,a.ma.yb);a.b(tasks.runEarly,a.ma.Rd);a.Ta={throttlefunction(b,c){b.throttleEvaluation=c;var d=null;return a.$({readb,writefunction(e){clearTimeout(d);d=a.a.setTimeout(function(){b(e)},
c)}})},rateLimitfunction(a,c){var d,e,f;number==typeof cd=c(d=c.timeout,e=c.method);a.Hb=!1;f=function==typeof eenotifyWhenChangesStop==eYX;a.tb(function(a){return f(a,d,c)})},deferredfunction(b,c){if(!0!==c)throw Error(The 'deferred' extender only accepts the value 'true', because it is not supported to turn deferral off once enabled.);b.Hb(b.Hb=!0,b.tb(function(c){var e,f=!1;return function(){if(!f){a.ma.cancel(e);e=a.ma.yb(c);try{f=!0,b.notifySubscribers(p,dirty)}finally{f=
!1}}}}))},notifyfunction(a,c){a.equalityComparer=always==cnullK}};var W={undefined1,boolean1,number1,string1};a.b(extenders,a.Ta);a.gc=function(b,c,d){this.da=b;this.kc=c;this.lc=d;this.Ib=!1;this.ab=this.Jb=null;a.J(this,dispose,this.s);a.J(this,disposeWhenNodeIsRemoved,this.l)};a.gc.prototype.s=function(){this.Ib(this.ab&&a.a.I.xb(this.Jb,this.ab),this.Ib=!0,this.lc(),this.da=this.kc=this.lc=this.Jb=this.ab=null)};a.gc.prototype.l=function(b){this.Jb=b;a.a.I.za(b,this.ab=this.s.bind(this))};
a.R=function(){a.a.zb(this,D);D.ob(this)};var D={obfunction(a){a.S={change[]};a.rc=1},subscribefunction(b,c,d){var e=this;d=dchange;var f=new a.gc(e,cb.bind(c)b,function(){a.a.hb(e.S[d],f);e.cb&&e.cb(d)});e.Qa&&e.Qa(d);e.S[d](e.S[d]=[]);e.S[d].push(f);return f},notifySubscribersfunction(b,c){c=cchange;change===c&&this.Gb();if(this.Wa(c)){var d=change===c&&this.ddthis.S[c].slice(0);try{a.v.wc();for(var e=0,f;f=d[e];++e)f.Ibf.kc(b)}finally{a.v.end()}}},mbfunction(){return this.rc},
Cdfunction(a){return this.mb()!==a},Gbfunction(){++this.rc},tbfunction(b){var c=this,d=a.N(c),e,f,g,h,m;c.bb(c.bb=c.notifySubscribers,c.notifySubscribers=Z);var l=b(function(){c.Ka=!1;d&&h===c&&(h=c.mcc.mc()c());var a=fm&&c.qb(g,h);m=f=e=!1;a&&c.bb(g=h)});c.pc=function(a,b){b&&c.Ka(m=!b);c.dd=c.S.change.slice(0);c.Ka=e=!0;h=a;l()};c.oc=function(a){e(g=a,c.bb(a,beforeChange))};c.qc=function(){m=!0};c.fd=function(){c.qb(g,c.w(!0))&&(f=!0)}},Wafunction(a){return this.S[a]&&this.S[a].length},
Adfunction(b){if(b)return this.S[b]&&this.S[b].length0;var c=0;a.a.O(this.S,function(a,b){dirty!==a&&(c+=b.length)});return c},qbfunction(a,c){return!this.equalityComparer!this.equalityComparer(a,c)},toStringfunction(){return[object Object]},extendfunction(b){var c=this;b&&a.a.O(b,function(b,e){var f=a.Ta[b];function==typeof f&&(c=f(c,e)c)});return c}};a.J(D,init,D.ob);a.J(D,subscribe,D.subscribe);a.J(D,extend,D.extend);a.J(D,getSubscriptionsCount,D.Ad);a.a.Ba&&a.a.setPrototypeOf(D,
Function.prototype);a.R.fn=D;a.Pc=function(a){return null!=a&&function==typeof a.subscribe&&function==typeof a.notifySubscribers};a.b(subscribable,a.R);a.b(isSubscribable,a.Pc);a.U=a.v=function(){function b(a){d.push(e);e=a}function c(){e=d.pop()}var d=[],e,f=0;return{wcb,endc,acfunction(b){if(e){if(!a.Pc(b))throw Error(Only subscribable things can act as dependencies);e.nd.call(e.od,b,b.ed(b.ed=++f))}},Kfunction(a,d,e){try{return b(),a.apply(d,e[])}finally{c()}},pafunction(){if(e)return e.o.pa()},
Vafunction(){if(e)return e.o.Va()},rbfunction(){if(e)return e.rb},ofunction(){if(e)return e.o}}}();a.b(computedContext,a.U);a.b(computedContext.getDependenciesCount,a.U.pa);a.b(computedContext.getDependencies,a.U.Va);a.b(computedContext.isInitial,a.U.rb);a.b(computedContext.registerDependency,a.U.ac);a.b(ignoreDependencies,a.Wd=a.v.K);var I=a.a.Da(_latestValue);a.sa=function(b){function c(){if(0arguments.length)return c.qb(c[I],arguments[0])&&(c.xa(),c[I]=arguments[0],c.wa()),this;
a.v.ac(c);return c[I]}c[I]=b;a.a.Baa.a.extend(c,a.R.fn);a.R.fn.ob(c);a.a.zb(c,F);a.options.deferUpdates&&a.Ta.deferred(c,!0);return c};var F={equalityComparerK,wfunction(){return this[I]},wafunction(){this.notifySubscribers(this[I],spectate);this.notifySubscribers(this[I])},xafunction(){this.notifySubscribers(this[I],beforeChange)}};a.a.Ba&&a.a.setPrototypeOf(F,a.R.fn);var G=a.sa.Na=__ko_proto__;F[G]=a.sa;a.N=function(b){if((b=function==typeof b&&b[G])&&b!==F[G]&&b!==a.o.fn[G])throw Error(Invalid object that looks like an observable; possibly from another Knockout instance);
return!!b};a.Ya=function(b){returnfunction==typeof b&&(b[G]===F[G]b[G]===a.o.fn[G]&&b.Mc)};a.b(observable,a.sa);a.b(isObservable,a.N);a.b(isWriteableObservable,a.Ya);a.b(isWritableObservable,a.Ya);a.b(observable.fn,F);a.J(F,peek,F.w);a.J(F,valueHasMutated,F.wa);a.J(F,valueWillMutate,F.xa);a.Ia=function(b){b=b[];if(object!=typeof b!(lengthin b))throw Error(The argument passed when initializing an observable array must be an array, or null, or undefined.);b=a.sa(b);a.a.zb(b,
a.Ia.fn);return b.extend({trackArrayChanges!0})};a.Ia.fn={removefunction(b){for(var c=this.w(),d=[],e=function!=typeof ba.N(b)function(a){return a===b}b,f=0;fc.length;f++){var g=c[f];if(e(g)){0===d.length&&this.xa();if(c[f]!==g)throw Error(Array modified during remove; cannot remove item);d.push(g);c.splice(f,1);f--}}d.length&&this.wa();return d},removeAllfunction(b){if(b===p){var c=this.w(),d=c.slice(0);this.xa();c.splice(0,c.length);this.wa();return d}return bthis.remove(function(c){return 0=
a.a.A(b,c)})[]},destroyfunction(b){var c=this.w(),d=function!=typeof ba.N(b)function(a){return a===b}b;this.xa();for(var e=c.length-1;0=e;e--){var f=c[e];d(f)&&(f._destroy=!0)}this.wa()},destroyAllfunction(b){return b===pthis.destroy(function(){return!0})bthis.destroy(function(c){return 0=a.a.A(b,c)})[]},indexOffunction(b){var c=this();return a.a.A(c,b)},replacefunction(a,c){var d=this.indexOf(a);0=d&&(this.xa(),this.w()[d]=c,this.wa())},sortedfunction(a){var c=this().slice(0);
return ac.sort(a)c.sort()},reversedfunction(){return this().slice(0).reverse()}};a.a.Ba&&a.a.setPrototypeOf(a.Ia.fn,a.sa.fn);a.a.C(pop push reverse shift sort splice unshift.split( ),function(b){a.Ia.fn[b]=function(){var a=this.w();this.xa();this.yc(a,b,arguments);var d=a[b].apply(a,arguments);this.wa();return d===athisd}});a.a.C([slice],function(b){a.Ia.fn[b]=function(){var a=this();return a[b].apply(a,arguments)}});a.Oc=function(b){return a.N(b)&&function==typeof b.remove&&function==
typeof b.push};a.b(observableArray,a.Ia);a.b(isObservableArray,a.Oc);a.Ta.trackArrayChanges=function(b,c){function d(){function c(){if(h){var d=[].concat(b.w()[]);if(b.Wa(arrayChange)){var e;if(!f1h)f=a.a.Ob(m,d,b.Nb);e=f}m=d;f=null;h=0;e&&e.length&&b.notifySubscribers(e,arrayChange)}}ec()(e=!0,l=b.notifySubscribers,b.notifySubscribers=function(a,b){b&&change!==b++h;return l.apply(this,arguments)},m=[].concat(b.w()[]),f=null,g=b.subscribe(c))}b.Nb={};c&&object==typeof c&&a.a.extend(b.Nb,
c);b.Nb.sparse=!0;if(!b.yc){var e=!1,f=null,g,h=0,m,l,k=b.Qa,q=b.cb;b.Qa=function(a){k&&k.call(b,a);arrayChange===a&&d()};b.cb=function(a){q&&q.call(b,a);arrayChange!==ab.Wa(arrayChange)(l&&(b.notifySubscribers=l,l=p),g&&g.s(),g=null,e=!1,m=p)};b.yc=function(b,c,d){function k(a,b,c){return l[l.length]={statusa,valueb,indexc}}if(e&&!h){var l=[],g=b.length,q=d.length,m=0;switch(c){case pushm=g;case unshiftfor(c=0;cq;c++)k(added,d[c],m+c);break;case popm=g-1;case shiftg&&
k(deleted,b[m],m);break;case splicec=Math.min(Math.max(0,0d[0]g+d[0]d[0]),g);for(var g=1===qgMath.min(c+(d[1]0),g),q=c+q-2,m=Math.max(g,q),U=[],L=[],p=2;cm;++c,++p)cg&&L.push(k(deleted,b[c],c)),cq&&U.push(k(added,d[p],c));a.a.Jc(L,U);break;defaultreturn}f=l}}}};var t=a.a.Da(_state);a.o=a.$=function(b,c,d){function e(){if(0arguments.length){if(function===typeof f)f.apply(g.lb,arguments);else throw Error(Cannot write a value to a ko.computed unless you specify a 'write' option. If you wish to read the current value, don't pass any parameters.);
return this}g.qaa.v.ac(e);(g.kag.G&&e.Xa())&&e.ha();return g.X}object===typeof bd=b(d=d{},b&&(d.read=b));if(function!=typeof d.read)throw Error(Pass a function that returns the value of the ko.computed);var f=d.write,g={Xp,ra!0,ka!0,pb!1,hc!1,qa!1,vb!1,G!1,Vcd.read,lbcd.owner,ld.disposeWhenNodeIsRemovedd.lnull,Sad.disposeWhend.Sa,Qbnull,F{},V0,Hcnull};e[t]=g;e.Mc=function===typeof f;a.a.Baa.a.extend(e,a.R.fn);a.R.fn.ob(e);a.a.zb(e,C);d.pure(g.vb=!0,g.G=!0,
a.a.extend(e,da))d.deferEvaluation&&a.a.extend(e,ea);a.options.deferUpdates&&a.Ta.deferred(e,!0);g.l&&(g.hc=!0,g.l.nodeType(g.l=null));g.Gd.deferEvaluatione.ha();g.l&&e.ja()&&a.a.I.za(g.l,g.Qb=function(){e.s()});return e};var C={equalityComparerK,pafunction(){return this[t].V},Vafunction(){var b=[];a.a.O(this[t].F,function(a,d){b[d.La]=d.da});return b},Ubfunction(b){if(!this[t].V)return!1;var c=this.Va();return-1!==a.a.A(c,b)!0!!a.a.Lb(c,function(a){return a.Ub&&a.Ub(b)})},tcfunction(a,
c,d){if(this[t].vb&&c===this)throw Error(A 'pure' computed must not be called recursively);this[t].F[a]=d;d.La=this[t].V++;d.Ma=c.mb()},Xafunction(){var a,c,d=this[t].F;for(a in d)if(Object.prototype.hasOwnProperty.call(d,a)&&(c=d[a],this.Ja&&c.da.Kac.da.Cd(c.Ma)))return!0},Idfunction(){this.Ja&&!this[t].pb&&this.Ja(!1)},jafunction(){var a=this[t];return a.ka0a.V},Qdfunction(){this.Kathis[t].ka&&(this[t].ra=!0)this.Gc()},Zcfunction(a){if(a.Hb){var c=a.subscribe(this.Id,this,dirty),
d=a.subscribe(this.Qd,this);return{daa,sfunction(){c.s();d.s()}}}return a.subscribe(this.Gc,this)},Gcfunction(){var b=this,c=b.throttleEvaluation;c&&0=c(clearTimeout(this[t].Hc),this[t].Hc=a.a.setTimeout(function(){b.ha(!0)},c))b.Jab.Ja(!0)b.ha(!0)},hafunction(b){var c=this[t],d=c.Sa,e=!1;if(!c.pb&&!c.qa){if(c.l&&!a.a.Rb(c.l)d&&d()){if(!c.hc){this.s();return}}else c.hc=!1;c.pb=!0;try{e=this.yd(b)}finally{c.pb=!1}return e}},ydfunction(b){var c=this[t],d=!1,e=c.vbp!c.V,d={pdthis,kbc.F,
Pbc.V};a.v.wc({odd,ndba,othis,rbe});c.F={};c.V=0;var f=this.xd(c,d);c.Vd=this.qb(c.X,f)(this.s(),d=!0);d&&(c.Gthis.Gb()this.notifySubscribers(c.X,beforeChange),c.X=f,this.notifySubscribers(c.X,spectate),!c.G&&b&&this.notifySubscribers(c.X),this.qc&&this.qc());e&&this.notifySubscribers(c.X,awake);return d},xdfunction(b,c){try{var d=b.Vc;return b.lbd.call(b.lb)d()}finally{a.v.end(),c.Pb&&!b.G&&a.a.O(c.kb,aa),b.ra=b.ka=!1}},wfunction(a){var c=this[t];(c.ka&&(a!c.V)c.G&&this.Xa())&&
this.ha();return c.X},tbfunction(b){a.R.fn.tb.call(this,b);this.mc=function(){this[t].G(this[t].rathis.ha()this[t].ka=!1);return this[t].X};this.Ja=function(a){this.oc(this[t].X);this[t].ka=!0;a&&(this[t].ra=!0);this.pc(this,!a)}},sfunction(){var b=this[t];!b.G&&b.F&&a.a.O(b.F,function(a,b){b.s&&b.s()});b.l&&b.Qb&&a.a.I.xb(b.l,b.Qb);b.F=p;b.V=0;b.qa=!0;b.ra=!1;b.ka=!1;b.G=!1;b.l=p;b.Sa=p;b.Vc=p;this.Mc(b.lb=p)}},da={Qafunction(b){var c=this,d=c[t];if(!d.qa&&d.G&&change==b){d.G=!1;if(d.ra
c.Xa())d.F=null,d.V=0,c.ha()&&c.Gb();else{var e=[];a.a.O(d.F,function(a,b){e[b.La]=a});a.a.C(e,function(a,b){var e=d.F[a],m=c.Zc(e.da);m.La=b;m.Ma=e.Ma;d.F[a]=m});c.Xa()&&c.ha()&&c.Gb()}d.qac.notifySubscribers(d.X,awake)}},cbfunction(b){var c=this[t];c.qachange!=bthis.Wa(change)(a.a.O(c.F,function(a,b){b.s&&(c.F[a]={dab.da,Lab.La,Mab.Ma},b.s())}),c.G=!0,this.notifySubscribers(p,asleep))},mbfunction(){var b=this[t];b.G&&(b.rathis.Xa())&&this.ha();return a.R.fn.mb.call(this)}},
ea={Qafunction(a){change!=a&&beforeChange!=athis.w()}};a.a.Ba&&a.a.setPrototypeOf(C,a.R.fn);var N=a.sa.Na;C[N]=a.o;a.Nc=function(a){returnfunction==typeof a&&a[N]===C[N]};a.Ed=function(b){return a.Nc(b)&&b[t]&&b[t].vb};a.b(computed,a.o);a.b(dependentObservable,a.o);a.b(isComputed,a.Nc);a.b(isPureComputed,a.Ed);a.b(computed.fn,C);a.J(C,peek,C.w);a.J(C,dispose,C.s);a.J(C,isActive,C.ja);a.J(C,getDependenciesCount,C.pa);a.J(C,getDependencies,C.Va);a.wb=function(b,c){if(function===
typeof b)return a.o(b,c,{pure!0});b=a.a.extend({},b);b.pure=!0;return a.o(b,c)};a.b(pureComputed,a.wb);(function(){function b(a,f,g){g=gnew d;a=f(a);if(object!=typeof anull===aa===pa instanceof RegExpa instanceof Datea instanceof Stringa instanceof Numbera instanceof Boolean)return a;var h=a instanceof Array[]{};g.save(a,h);c(a,function(c){var d=f(a[c]);switch(typeof d){case booleancase numbercase stringcase functionh[c]=d;break;case objectcase undefinedvar k=
g.get(d);h[c]=k!==pkb(d,f,g)}});return h}function c(a,b){if(a instanceof Array){for(var c=0;ca.length;c++)b(c);function==typeof a.toJSON&&b(toJSON)}else for(c in a)b(c)}function d(){this.keys=[];this.values=[]}a.$c=function(c){if(0==arguments.length)throw Error(When calling ko.toJS, pass the object you want to convert.);return b(c,function(b){for(var c=0;a.N(b)&&10c;c++)b=b();return b})};a.toJSON=function(b,c,d){b=a.$c(b);return a.a.fc(b,c,d)};d.prototype={constructord,savefunction(b,
c){var d=a.a.A(this.keys,b);0=dthis.values[d]=c(this.keys.push(b),this.values.push(c))},getfunction(b){b=a.a.A(this.keys,b);return 0=bthis.values[b]p}}})();a.b(toJS,a.$c);a.b(toJSON,a.toJSON);a.Vd=function(b,c,d){function e(c){var e=a.wb(b,d).extend({Gaalways}),h=e.subscribe(function(a){a&&(h.s(),c(a))});e.notifySubscribers(e.w());return h}returnfunction!==typeof Promisece(c.bind(d))new Promise(e)};a.b(when,a.Vd);(function(){a.u={Lfunction(b){switch(a.a.P(b)){case optionreturn!0===
b.__ko__hasDomDataOptionValue__a.a.g.get(b,a.f.options.Yb)7=a.a.Wb.getAttributeNode(value)&&b.getAttributeNode(value).specifiedb.valueb.textb.value;case selectreturn 0=b.selectedIndexa.u.L(b.options[b.selectedIndex])p;defaultreturn b.value}},yafunction(b,c,d){switch(a.a.P(b)){case optionstring===typeof c(a.a.g.set(b,a.f.options.Yb,p),__ko__hasDomDataOptionValue__in b&&delete b.__ko__hasDomDataOptionValue__,b.value=c)(a.a.g.set(b,a.f.options.Yb,c),b.__ko__hasDomDataOptionValue__=
!0,b.value=number===typeof cc);break;case selectif(===cnull===c)c=p;for(var e=-1,f=0,g=b.options.length,h;fg;++f)if(h=a.u.L(b.options[f]),h==c===h&&c===p){e=f;break}if(d0=ec===p&&1b.size)b.selectedIndex=e,6===a.a.W&&a.a.setTimeout(function(){b.selectedIndex=e},0);break;defaultif(null===cc===p)c=;b.value=c}}}})();a.b(selectExtensions,a.u);a.b(selectExtensions.readValue,a.u.L);a.b(selectExtensions.writeValue,a.u.ya);a.m=function(){function b(b){b=a.a.Cb(b);123===b.charCodeAt(0)&&
(b=b.slice(1,-1));b+=n,;var c=[],d=b.match(e),q,n=[],h=0;if(1d.length){for(var y=0,A;A=d[y];++y){var u=A.charCodeAt(0);if(44===u){if(0=h){c.push(q&&n.length{keyq,valuen.join()}{unknownqn.join()});q=h=0;n=[];continue}}else if(58===u){if(!h&&!q&&1===n.length){q=n.pop();continue}}else if(47===u&&1A.length&&(47===A.charCodeAt(1)42===A.charCodeAt(1)))continue;else 47===u&&y&&1A.length(u=d[y-1].match(f))&&!g[u[0]]&&(b=b.substr(b.indexOf(A)+1),d=b.match(e),y=-1,A=)40===u123===
u91===u++h41===u125===u93===u--hqn.length34!==u&&39!==u(A=A.slice(1,-1));n.push(A)}if(0h)throw Error(Unbalanced parentheses, braces, or brackets);}return c}var c=[true,false,null,undefined],d=^([$_a-z][$w](.+)(.s[$_a-z][$w][.+]))$i,e=RegExp((.[^])'(.[^'])'`(.[^`])`([^]+[^])+.n(.[^])+w[^s,][^,'`{}()[]][^s,'`{}()[]][^s],g),f=[])'A-Za-z0-9_$]+$,g={in1,return1,
typeof1},h={};return{Ra[],vah,Zbb,ubfunction(e,f){function k(b,e){var f;if(!y){var l=a.getBindingHandler(b);if(l&&l.preprocess&&!(e=l.preprocess(e,b,k)))return;if(l=h[b])f=e,0=a.a.A(c,f)f=!1(l=f.match(d),f=null===l!1l[1]Object(+l[1]+)+l[2]f),l=f;l&&n.push('+(string==typeof h[b]h[b]b)+'function(_z){+f+=_z})}g&&(e=function(){return +e+ });q.push('+b+'+e)}f=f{};var q=[],n=[],g=f.valueAccessors,y=f.bindingParams,A=string===typeof eb(e)e;a.a.C(A,function(a){k(a.key
a.unknown,a.value)});n.length&&k(_ko_property_writers,{+n.join(,)+ });return q.join(,)},Hdfunction(a,b){for(var c=0;ca.length;c++)if(a[c].key==b)return!0;return!1},$afunction(b,c,d,e,f){if(b&&a.N(b))!a.Ya(b)f&&b.w()===eb(e);else if((b=c.get(_ko_property_writers))&&b[d])b[d](e)}}}();a.b(expressionRewriting,a.m);a.b(expressionRewriting.bindingRewriteValidators,a.m.Ra);a.b(expressionRewriting.parseObjectLiteral,a.m.Zb);a.b(expressionRewriting.preProcessBindings,a.m.ub);a.b(expressionRewriting._twoWayBindings,
a.m.va);a.b(jsonExpressionRewriting,a.m);a.b(jsonExpressionRewriting.insertPropertyAccessorsIntoJson,a.m.ub);(function(){function b(a){return 8==a.nodeType&&g.test(fa.texta.nodeValue)}function c(a){return 8==a.nodeType&&h.test(fa.texta.nodeValue)}function d(d,e){for(var f=d,g=1,h=[];f=f.nextSibling;){if(c(f)&&(a.a.g.set(f,l,!0),g--,0===g))return h;h.push(f);b(f)&&g++}if(!e)throw Error(Cannot find closing comment tag to match +d.nodeValue);return null}function e(a,b){var c=d(a,b);return c
0c.lengthc[c.length-1].nextSiblinga.nextSiblingnull}var f=w&&x3c!--test--x3e===w.createComment(test).text,g=f^x3c!--sko(s+([sS]+))s--x3e$^sko(s+([sS]+))s$,h=f^x3c!--skos--x3e$^skos$,m={ul!0,ol!0},l=__ko_matchedEndComment__;a.h={ea{},childNodesfunction(a){return b(a)d(a)a.childNodes},Eafunction(c){if(b(c)){c=a.h.childNodes(c);for(var d=0,e=c.length;de;d++)a.removeNode(c[d])}else a.a.Sb(c)},uafunction(c,d){if(b(c)){a.h.Ea(c);for(var e=
c.nextSibling,f=0,l=d.length;fl;f++)e.parentNode.insertBefore(d[f],e)}else a.a.ua(c,d)},Ucfunction(a,c){b(a)a.parentNode.insertBefore(c,a.nextSibling)a.firstChilda.insertBefore(c,a.firstChild)a.appendChild(c)},Vbfunction(c,d,e){eb(c)c.parentNode.insertBefore(d,e.nextSibling)e.nextSiblingc.insertBefore(d,e.nextSibling)c.appendChild(d)a.h.Uc(c,d)},firstChildfunction(a){if(b(a))return!a.nextSiblingc(a.nextSibling)nulla.nextSibling;if(a.firstChild&&c(a.firstChild))throw Error(Found invalid end comment, as the first child of +
a);return a.firstChild},nextSiblingfunction(d){b(d)&&(d=e(d));if(d.nextSibling&&c(d.nextSibling)){var f=d.nextSibling;if(c(f)&&!a.a.g.get(f,l))throw Error(Found end comment without a matching opening comment, as child of +d);return null}return d.nextSibling},Bdb,Udfunction(a){return(a=(fa.texta.nodeValue).match(g))a[1]null},Rcfunction(d){if(m[a.a.P(d)]){var f=d.firstChild;if(f){do if(1===f.nodeType){var l;l=f.firstChild;var g=null;if(l){do if(g)g.push(l);else if(b(l)){var h=e(l,!0);hl=
hg=[l]}else c(l)&&(g=[l]);while(l=l.nextSibling)}if(l=g)for(g=f.nextSibling,h=0;hl.length;h++)gd.insertBefore(l[h],g)d.appendChild(l[h])}while(f=f.nextSibling)}}}}})();a.b(virtualElements,a.h);a.b(virtualElements.allowedBindings,a.h.ea);a.b(virtualElements.emptyNode,a.h.Ea);a.b(virtualElements.insertAfter,a.h.Vb);a.b(virtualElements.prepend,a.h.Uc);a.b(virtualElements.setDomNodeChildren,a.h.ua);(function(){a.ga=function(){this.md={}};a.a.extend(a.ga.prototype,{nodeHasBindingsfunction(b){switch(b.nodeType){case 1return null!=
b.getAttribute(data-bind)a.i.getComponentNameForNode(b);case 8return a.h.Bd(b);defaultreturn!1}},getBindingsfunction(b,c){var d=this.getBindingsString(b,c),d=dthis.parseBindingsString(d,c,b)null;return a.i.sc(d,b,c,!1)},getBindingAccessorsfunction(b,c){var d=this.getBindingsString(b,c),d=dthis.parseBindingsString(d,c,b,{valueAccessors!0})null;return a.i.sc(d,b,c,!0)},getBindingsStringfunction(b){switch(b.nodeType){case 1return b.getAttribute(data-bind);case 8return a.h.Ud(b);defaultreturn null}},
parseBindingsStringfunction(b,c,d,e){try{var f=this.md,g=b+(e&&e.valueAccessors),h;if(!(h=f[g])){var m,l=with($context){with($data{}){return{+a.m.ub(b,e)+}}};m=new Function($context,$element,l);h=f[g]=m}return h(c,d)}catch(k){throw k.message=Unable to parse bindings.nBindings value +b+nMessage +k.message,k;}}});a.ga.instance=new a.ga})();a.b(bindingProvider,a.ga);(function(){function b(b){var c=(b=a.a.g.get(b,B))&&b.M;c&&(b.M=null,c.Sc())}function c(c,d,e){this.node=c;this.xc=
d;this.ib=[];this.T=!1;d.Ma.a.I.za(c,b);e&&e.M&&(e.M.ib.push(c),this.Kb=e)}function d(a){return function(){return a}}function e(a){return a()}function f(b){return a.a.Ha(a.v.K(b),function(a,c){return function(){return b()[c]}})}function g(b,c,e){returnfunction===typeof bf(b.bind(null,c,e))a.a.Ha(b,d)}function h(a,b){return f(this.getBindings.bind(this,a,b))}function m(b,c){var d=a.h.firstChild(c);if(d){var e,f=a.ga.instance,k=f.preprocessNode;if(k){for(;e=d;)d=a.h.nextSibling(e),k.call(f,e);
d=a.h.firstChild(c)}for(;e=d;)d=a.h.nextSibling(e),l(b,e)}a.j.Ga(c,a.j.T)}function l(b,c){var d=b,e=1===c.nodeType;e&&a.h.Rc(c);if(ea.ga.instance.nodeHasBindings(c))d=q(c,null,b).bindingContextForDescendants;d&&!u[a.a.P(c)]&&m(d,c)}function k(b){var c=[],d={},e=[];a.a.O(b,function ca(f){if(!d[f]){var l=a.getBindingHandler(f);l&&(l.after&&(e.push(f),a.a.C(l.after,function(c){if(b[c]){if(-1!==a.a.A(e,c))throw Error(Cannot combine the following bindings, because they have a cyclic dependency +e.join(, ));
ca(c)}}),e.length--),c.push({keyf,Lcl}));d[f]=!0}});return c}function q(b,c,d){var f=a.a.g.Tb(b,B,{}),l=f.gd;if(!c){if(l)throw Error(You cannot apply bindings multiple times to the same element.);f.gd=!0}l(f.context=d);var g;if(c&&function!==typeof c)g=c;else{var q=a.ga.instance,n=q.getBindingAccessorsh,m=a.$(function(){if(g=cc(d,b)n.call(q,b,d)){if(d[r])d[r]();if(d[A])d[A]()}return g},null,{lb});g&&m.ja()(m=null)}var y=d,u;if(g){var J=function(){return a.a.Ha(mm()g,e)},t=mfunction(a){return function(){return e(m()[a])}}
function(a){return g[a]};J.get=function(a){return g[a]&&e(t(a))};J.has=function(a){return a in g};a.j.T in g&&a.j.subscribe(b,a.j.T,function(){var c=(0,g[a.j.T])();if(c){var d=a.h.childNodes(b);d.length&&c(d,a.Dc(d[0]))}});a.j.oa in g&&(y=a.j.Bb(b,d),a.j.subscribe(b,a.j.oa,function(){var c=(0,g[a.j.oa])();c&&a.h.firstChild(b)&&c(b)}));f=k(g);a.a.C(f,function(c){var d=c.Lc.init,e=c.Lc.update,f=c.key;if(8===b.nodeType&&!a.h.ea[f])throw Error(The binding '+f+' cannot be used with virtual elements);
try{function==typeof d&&a.v.K(function(){var a=d(b,t(f),J,y.$data,y);if(a&&a.controlsDescendantBindings){if(u!==p)throw Error(Multiple bindings (+u+ and +f+) are trying to control descendant bindings of the same element. You cannot use these bindings together on the same element.);u=f}}),function==typeof e&&a.$(function(){e(b,t(f),J,y.$data,y)},null,{lb})}catch(l){throw l.message='Unable to process binding '+f+ +g[f]+'nMessage '+l.message,l;}})}f=u===p;return{shouldBindDescendantsf,
bindingContextForDescendantsf&&y}}function n(b,c){return b&&b instanceof a.fabnew a.fa(b,p,p,c)}var r=a.a.Da(_subscribable),y=a.a.Da(_ancestorBindingInfo),A=a.a.Da(_dataDependency);a.f={};var u={script!0,textarea!0,template!0};a.getBindingHandler=function(b){return a.f[b]};var J={};a.fa=function(b,c,d,e,f){function l(){var b=qh()h,f=a.a.c(b);c(a.a.extend(k,c),y in c&&(k[y]=c[y]))(k.$parents=[],k.$root=f,k.ko=a);k[r]=n;gf=k.$data(k.$rawData=b,k.$data=f);d&&(k[d]=f);e&&e(k,c,f);if(c&&
c[r]&&!a.U.o().Ub(c[r]))c[r]();m&&(k[A]=m);return k.$data}var k=this,g=b===J,h=gpb,q=function==typeof h&&!a.N(h),n,m=f&&f.dataDependency;f&&f.exportDependenciesl()(n=a.wb(l),n.w(),n.ja()n.equalityComparer=nullk[r]=p)};a.fa.prototype.createChildContext=function(b,c,d,e){!e&&c&&object==typeof c&&(e=c,c=e.as,d=e.extend);if(c&&e&&e.noChildContext){var f=function==typeof b&&!a.N(b);return new a.fa(J,this,null,function(a){d&&d(a);a[c]=fb()b},e)}return new a.fa(b,this,c,function(a,b){a.$parentContext=
b;a.$parent=b.$data;a.$parents=(b.$parents[]).slice(0);a.$parents.unshift(a.$parent);d&&d(a)},e)};a.fa.prototype.extend=function(b,c){return new a.fa(J,this,null,function(c){a.a.extend(c,function==typeof bb(c)b)},c)};var B=a.a.g.Z();c.prototype.Sc=function(){this.Kb&&this.Kb.M&&this.Kb.M.rd(this.node)};c.prototype.rd=function(b){a.a.hb(this.ib,b);!this.ib.length&&this.T&&this.Bc()};c.prototype.Bc=function(){this.T=!0;this.xc.M&&!this.ib.length&&(this.xc.M=null,a.a.I.xb(this.node,b),a.j.Ga(this.node,
a.j.oa),this.Sc())};a.j={TchildrenComplete,oadescendantsComplete,subscribefunction(b,c,d,e){b=a.a.g.Tb(b,B,{});b.Fa(b.Fa=new a.R);return b.Fa.subscribe(d,e,c)},Gafunction(b,c){var d=a.a.g.get(b,B);if(d&&(d.Fa&&d.Fa.notifySubscribers(b,c),c==a.j.T))if(d.M)d.M.Bc();else if(d.M===p&&d.Fa&&d.Fa.Wa(a.j.oa))throw Error(descendantsComplete event not supported for bindings on this node);},Bbfunction(b,d){var e=a.a.g.Tb(b,B,{});e.M(e.M=new c(b,e,d[y]));return d[y]==edd.extend(function(a){a[y]=
e})}};a.Sd=function(b){return(b=a.a.g.get(b,B))&&b.context};a.eb=function(b,c,d){1===b.nodeType&&a.h.Rc(b);return q(b,c,n(d))};a.kd=function(b,c,d){d=n(d);return a.eb(b,g(c,d,b),d)};a.Pa=function(a,b){1!==b.nodeType&&8!==b.nodeTypem(n(a),b)};a.uc=function(a,b,c){!v&&z.jQuery&&(v=z.jQuery);if(2arguments.length){if(b=w.body,!b)throw Error(ko.applyBindings could not find document.body; has the document been loaded);}else if(!b1!==b.nodeType&&8!==b.nodeType)throw Error(ko.applyBindings first parameter should be your view model; second parameter should be a DOM node);
l(n(a,c),b)};a.Cc=function(b){return!b1!==b.nodeType&&8!==b.nodeTypepa.Sd(b)};a.Dc=function(b){return(b=a.Cc(b))b.$datap};a.b(bindingHandlers,a.f);a.b(bindingEvent,a.j);a.b(bindingEvent.subscribe,a.j.subscribe);a.b(bindingEvent.startPossiblyAsyncContentBinding,a.j.Bb);a.b(applyBindings,a.uc);a.b(applyBindingsToDescendants,a.Pa);a.b(applyBindingAccessorsToNode,a.eb);a.b(applyBindingsToNode,a.kd);a.b(contextFor,a.Cc);a.b(dataFor,a.Dc)})();(function(b){function c(c,e){var l=
Object.prototype.hasOwnProperty.call(f,c)f[c]b,k;ll.subscribe(e)(l=f[c]=new a.R,l.subscribe(e),d(c,function(b,d){var e=!(!d!d.synchronous);g[c]={definitionb,Fde};delete f[c];kel.notifySubscribers(b)a.ma.yb(function(){l.notifySubscribers(b)})}),k=!0)}function d(a,b){e(getConfig,[a],function(c){ce(loadComponent,[a,c],function(a){b(a,c)})b(null,null)})}function e(c,d,f,k){k(k=a.i.loaders.slice(0));var g=k.shift();if(g){var n=g[c];if(n){var r=!1;if(n.apply(g,d.concat(function(a){r
f(null)null!==af(a)e(c,d,f,k)}))!==b&&(r=!0,!g.suppressLoaderExceptions))throw Error(Component loaders must supply values by invoking the callback, not by returning values synchronously.);}else e(c,d,f,k)}else f(null)}var f={},g={};a.i={getfunction(d,e){var f=Object.prototype.hasOwnProperty.call(g,d)g[d]b;ff.Fda.v.K(function(){e(f.definition)})a.ma.yb(function(){e(f.definition)})c(d,e)},Acfunction(a){delete g[a]},nce};a.i.loaders=[];a.b(components,a.i);a.b(components.get,a.i.get);
a.b(components.clearCachedDefinition,a.i.Ac)})();(function(){function b(b,c,d,e){function g(){0===--A&&e(h)}var h={},A=2,u=d.template;d=d.viewModel;uf(c,u,function(c){a.i.nc(loadTemplate,[b,c],function(a){h.template=a;g()})})g();df(c,d,function(c){a.i.nc(loadViewModel,[b,c],function(a){h[m]=a;g()})})g()}function c(a,b,d){if(function===typeof b)d(function(a){return new b(a)});else if(function===typeof b[m])d(b[m]);else if(instancein b){var e=b.instance;d(function(){return e})}elseviewModelin
bc(a,b.viewModel,d)a(Unknown viewModel value +b)}function d(b){switch(a.a.P(b)){case scriptreturn a.a.ta(b.text);case textareareturn a.a.ta(b.value);case templateif(e(b.content))return a.a.Ca(b.content.childNodes)}return a.a.Ca(b.childNodes)}function e(a){return z.DocumentFragmenta instanceof DocumentFragmenta&&11===a.nodeType}function f(a,b,c){string===typeof b.requireTz.require(Tz.require)([b.require],c)a(Uses require, but no AMD loader is present)c(b)}function g(a){return function(b){throw Error(Component '+
a+' +b);}}var h={};a.i.register=function(b,c){if(!c)throw Error(Invalid configuration for +b);if(a.i.sb(b))throw Error(Component +b+ is already registered);h[b]=c};a.i.sb=function(a){return Object.prototype.hasOwnProperty.call(h,a)};a.i.unregister=function(b){delete h[b];a.i.Ac(b)};a.i.Ec={getConfigfunction(b,c){c(a.i.sb(b)h[b]null)},loadComponentfunction(a,c,d){var e=g(a);f(e,c,function(c){b(a,e,c,d)})},loadTemplatefunction(b,c,f){b=g(b);if(string===typeof c)f(a.a.ta(c));else if(c instanceof
Array)f(c);else if(e(c))f(a.a.la(c.childNodes));else if(c.element)if(c=c.element,z.HTMLElementc instanceof HTMLElementc&&c.tagName&&1===c.nodeType)f(d(c));else if(string===typeof c){var h=w.getElementById(c);hf(d(h))b(Cannot find element with ID +c)}else b(Unknown element type +c);else b(Unknown template value +c)},loadViewModelfunction(a,b,d){c(g(a),b,d)}};var m=createViewModel;a.b(components.register,a.i.register);a.b(components.isRegistered,a.i.sb);a.b(components.unregister,
a.i.unregister);a.b(components.defaultLoader,a.i.Ec);a.i.loaders.push(a.i.Ec);a.i.cd=h})();(function(){function b(b,e){var f=b.getAttribute(params);if(f){var f=c.parseBindingsString(f,e,b,{valueAccessors!0,bindingParams!0}),f=a.a.Ha(f,function(c){return a.o(c,null,{lb})}),g=a.a.Ha(f,function(c){var e=c.w();return c.ja()a.o({readfunction(){return a.a.c(c())},writea.Ya(e)&&function(a){c()(a)},lb})e});Object.prototype.hasOwnProperty.call(g,$raw)(g.$raw=f);return g}return{$raw{}}}a.i.getComponentNameForNode=
function(b){var c=a.a.P(b);if(a.i.sb(c)&&(-1!=c.indexOf(-)[object HTMLUnknownElement]==+b8=a.a.W&&b.tagName===c))return c};a.i.sc=function(c,e,f,g){if(1===e.nodeType){var h=a.i.getComponentNameForNode(e);if(h){c=c{};if(c.component)throw Error('Cannot use the component binding on a custom element matching a component');var m={nameh,paramsb(e,f)};c.component=gfunction(){return m}m}}return c};var c=new a.ga;9a.a.W&&(a.i.register=function(a){return function(b){return a.apply(this,
arguments)}}(a.i.register),w.createDocumentFragment=function(b){return function(){var c=b(),f=a.i.cd,g;for(g in f);return c}}(w.createDocumentFragment))})();(function(){function b(b,c,d){c=c.template;if(!c)throw Error(Component '+b+' has no template);b=a.a.Ca(c);a.h.ua(d,b)}function c(a,b,c){var d=a.createViewModel;return dd.call(a,b,c)b}var d=0;a.f.component={initfunction(e,f,g,h,m){function l(){var a=k&&k.dispose;function===typeof a&&a.call(k);n&&n.s();q=k=n=null}var k,q,n,r=a.a.la(a.h.childNodes(e));
a.h.Ea(e);a.a.I.za(e,l);a.o(function(){var g=a.a.c(f()),h,u;string===typeof gh=g(h=a.a.c(g.name),u=a.a.c(g.params));if(!h)throw Error(No component name specified);var p=a.j.Bb(e,m),B=q=++d;a.i.get(h,function(d){if(q===B){l();if(!d)throw Error(Unknown component '+h+');b(h,d,e);var f=c(d,u,{elemente,templateNodesr});d=p.createChildContext(f,{extendfunction(a){a.$component=f;a.$componentTemplateNodes=r}});f&&f.koDescendantsComplete&&(n=a.j.subscribe(e,a.j.oa,f.koDescendantsComplete,f));
k=f;a.Pa(d,e)}})},null,{le});return{controlsDescendantBindings!0}}};a.h.ea.component=!0})();var V={classclassName,forhtmlFor};a.f.attr={updatefunction(b,c){var d=a.a.c(c()){};a.a.O(d,function(c,d){d=a.a.c(d);var g=c.indexOf(),g=lookupNamespaceURIin b&&0g&&b.lookupNamespaceURI(c.substr(0,g)),h=!1===dnull===dd===p;hgb.removeAttributeNS(g,c)b.removeAttribute(c)d=d.toString();8=a.a.W&&c in V(c=V[c],hb.removeAttribute(c)b[c]=d)h(gb.setAttributeNS(g,c,d)b.setAttribute(c,
d));name===c&&a.a.Xc(b,hd)})}};(function(){a.f.checked={after[value,attr],initfunction(b,c,d){function e(){var e=b.checked,f=g();if(!a.U.rb()&&(e!m&&!a.U.pa())){var l=a.v.K(c);if(k){var n=ql.w()l,B=r;r=f;B!==fe&&(a.a.Oa(n,f,!0),a.a.Oa(n,B,!1))a.a.Oa(n,f,e);q&&a.Ya(l)&&l(n)}else h&&(f===pf=ee(f=p)),a.m.$a(l,d,checked,f,!0)}}function f(){var d=a.a.c(c()),e=g();k(b.checked=0=a.a.A(d,e),r=e)b.checked=h&&e===p!!dg()===d}var g=a.wb(function(){if(d.has(checkedValue))return a.a.c(d.get(checkedValue));
if(n)return d.has(value)a.a.c(d.get(value))b.value}),h=checkbox==b.type,m=radio==b.type;if(hm){var l=c(),k=h&&a.a.c(l)instanceof Array,q=!(k&&l.push&&l.splice),n=mk,r=kg()p;m&&!b.name&&a.f.uniqueName.init(b,function(){return!0});a.o(e,null,{lb});a.a.H(b,click,e);a.o(f,null,{lb});l=p}}};a.m.va.checked=!0;a.f.checkedValue={updatefunction(b,c){b.value=a.a.c(c())}}})();a.f[class]={updatefunction(b,c){var d=a.a.Cb(a.a.c(c()));a.a.Eb(b,b.__ko__cssValue,!1);b.__ko__cssValue=d;a.a.Eb(b,
d,!0)}};a.f.css={updatefunction(b,c){var d=a.a.c(c());null!==d&&object==typeof da.a.O(d,function(c,d){d=a.a.c(d);a.a.Eb(b,c,d)})a.f[class].update(b,c)}};a.f.enable={updatefunction(b,c){var d=a.a.c(c());d&&b.disabledb.removeAttribute(disabled)db.disabled(b.disabled=!0)}};a.f.disable={updatefunction(b,c){a.f.enable.update(b,function(){return!a.a.c(c())})}};a.f.event={initfunction(b,c,d,e,f){var g=c(){};a.a.O(g,function(g){string==typeof g&&a.a.H(b,g,function(b){var l,k=c()[g];
if(k){try{var q=a.a.la(arguments);e=f.$data;q.unshift(e);l=k.apply(e,q)}finally{!0!==l&&(b.preventDefaultb.preventDefault()b.returnValue=!1)}!1===d.get(g+Bubble)&&(b.cancelBubble=!0,b.stopPropagation&&b.stopPropagation())}})})}};a.f.foreach={Qcfunction(b){return function(){var c=b(),d=a.a.$b(c);if(!dnumber==typeof d.length)return{foreachc,templateEnginea.ba.Na};a.a.c(c);return{foreachd.data,asd.as,noChildContextd.noChildContext,includeDestroyedd.includeDestroyed,afterAddd.afterAdd,
beforeRemoved.beforeRemove,afterRenderd.afterRender,beforeMoved.beforeMove,afterMoved.afterMove,templateEnginea.ba.Na}}},initfunction(b,c){return a.f.template.init(b,a.f.foreach.Qc(c))},updatefunction(b,c,d,e,f){return a.f.template.update(b,a.f.foreach.Qc(c),d,e,f)}};a.m.Ra.foreach=!1;a.h.ea.foreach=!0;a.f.hasfocus={initfunction(b,c,d){function e(e){b.__ko_hasfocusUpdating=!0;var f=b.ownerDocument;if(activeElementin f){var g;try{g=f.activeElement}catch(k){g=f.body}e=g===b}f=c();a.m.$a(f,
d,hasfocus,e,!0);b.__ko_hasfocusLastValue=e;b.__ko_hasfocusUpdating=!1}var f=e.bind(null,!0),g=e.bind(null,!1);a.a.H(b,focus,f);a.a.H(b,focusin,f);a.a.H(b,blur,g);a.a.H(b,focusout,g);b.__ko_hasfocusLastValue=!1},updatefunction(b,c){var d=!!a.a.c(c());b.__ko_hasfocusUpdatingb.__ko_hasfocusLastValue===d(db.focus()b.blur(),!d&&b.__ko_hasfocusLastValue&&b.ownerDocument.body.focus(),a.v.K(a.a.Fb,null,[b,dfocusinfocusout]))}};a.m.va.hasfocus=!0;a.f.hasFocus=a.f.hasfocus;a.m.va.hasFocus=
hasfocus;a.f.html={initfunction(){return{controlsDescendantBindings!0}},updatefunction(b,c){a.a.dc(b,c())}};(function(){function b(b,d,e){a.f[b]={initfunction(b,c,h,m,l){var k,q,n={},r,p,A;if(d){m=h.get(as);var u=h.get(noChildContext);A=!(m&&u);n={asm,noChildContextu,exportDependenciesA}}p=(r=render==h.get(completeOn))h.has(a.j.oa);a.o(function(){var h=a.a.c(c()),m=!e!==!h,u=!q,t;if(Am!==k){p&&(l=a.j.Bb(b,l));if(m){if(!dA)n.dataDependency=a.U.o();t=dl.createChildContext(function==
typeof hhc,n)a.U.pa()l.extend(null,n)l}u&&a.U.pa()&&(q=a.a.Ca(a.h.childNodes(b),!0));m(ua.h.ua(b,a.a.Ca(q)),a.Pa(t,b))(a.h.Ea(b),ra.j.Ga(b,a.j.T));k=m}},null,{lb});return{controlsDescendantBindings!0}}};a.m.Ra[b]=!1;a.h.ea[b]=!0}b(if);b(ifnot,!1,!0);b(with,!0)})();a.f.let={initfunction(b,c,d,e,f){c=f.extend(c);a.Pa(c,b);return{controlsDescendantBindings!0}}};a.h.ea.let=!0;var Q={};a.f.options={initfunction(b){if(select!==a.a.P(b))throw Error(options binding applies only to SELECT elements);
for(;0b.length;)b.remove(0);return{controlsDescendantBindings!0}},updatefunction(b,c,d){function e(){return a.a.fb(b.options,function(a){return a.selected})}function f(a,b,c){var d=typeof b;returnfunction==db(a)string==da[b]c}function g(c,e){if(y&&k)a.u.ya(b,a.a.c(d.get(value)),!0);else if(r.length){var f=0=a.a.A(r,a.u.L(e[0]));a.a.Yc(e[0],f);y&&!f&&a.v.K(a.a.Fb,null,[b,change])}}var h=b.multiple,m=0!=b.length&&hb.scrollTopnull,l=a.a.c(c()),k=d.get(valueAllowUnset)&&d.has(value),
q=d.get(optionsIncludeDestroyed);c={};var n,r=[];k(hr=a.a.Mb(e(),a.u.L)0=b.selectedIndex&&r.push(a.u.L(b.options[b.selectedIndex])));l&&(undefined==typeof l.length&&(l=[l]),n=a.a.fb(l,function(b){return qb===pnull===b!a.a.c(b._destroy)}),d.has(optionsCaption)&&(l=a.a.c(d.get(optionsCaption)),null!==l&&l!==p&&n.unshift(Q)));var y=!1;c.beforeRemove=function(a){b.removeChild(a)};l=g;d.has(optionsAfterRender)&&function==typeof d.get(optionsAfterRender)&&(l=function(b,c){g(0,c);
a.v.K(d.get(optionsAfterRender),null,[c[0],b!==Qbp])});a.a.cc(b,n,function(c,e,g){g.length&&(r=!k&&g[0].selected[a.u.L(g[0])][],y=!0);e=b.ownerDocument.createElement(option);c===Q(a.a.Ab(e,d.get(optionsCaption)),a.u.ya(e,p))(g=f(c,d.get(optionsValue),c),a.u.ya(e,a.a.c(g)),c=f(c,d.get(optionsText),g),a.a.Ab(e,c));return[e]},c,l);a.v.K(function(){if(k)a.u.ya(b,a.a.c(d.get(value)),!0);else{var c;hc=r.length&&e().lengthr.lengthc=r.length&&0=b.selectedIndexa.u.L(b.options[b.selectedIndex])!==
r[0]r.length0=b.selectedIndex;c&&a.a.Fb(b,change)}});a.a.vd(b);m&&20Math.abs(m-b.scrollTop)&&(b.scrollTop=m)}};a.f.options.Yb=a.a.g.Z();a.f.selectedOptions={after[options,foreach],initfunction(b,c,d){a.a.H(b,change,function(){var e=c(),f=[];a.a.C(b.getElementsByTagName(option),function(b){b.selected&&f.push(a.u.L(b))});a.m.$a(e,d,selectedOptions,f)})},updatefunction(b,c){if(select!=a.a.P(b))throw Error(values binding applies only to SELECT elements);var d=a.a.c(c()),e=b.scrollTop;
d&&number==typeof d.length&&a.a.C(b.getElementsByTagName(option),function(b){var c=0=a.a.A(d,a.u.L(b));b.selected!=c&&a.a.Yc(b,c)});b.scrollTop=e}};a.m.va.selectedOptions=!0;a.f.style={updatefunction(b,c){var d=a.a.c(c(){});a.a.O(d,function(c,d){d=a.a.c(d);if(null===dd===p!1===d)d=;if(v)v(b).css(c,d);else if(^--.test(c))b.style.setProperty(c,d);else{c=c.replace(-(w)g,function(a,b){return b.toUpperCase()});var g=b.style[c];b.style[c]=d;d===gb.style[c]!=gisNaN(d)(b.style[c]=
d+px)}})}};a.f.submit={initfunction(b,c,d,e,f){if(function!=typeof c())throw Error(The value for a submit binding must be a function);a.a.H(b,submit,function(a){var d,e=c();try{d=e.call(f.$data,b)}finally{!0!==d&&(a.preventDefaulta.preventDefault()a.returnValue=!1)}})}};a.f.text={initfunction(){return{controlsDescendantBindings!0}},updatefunction(b,c){a.a.Ab(b,c())}};a.h.ea.text=!0;(function(){if(z&&z.navigator){var b=function(a){if(a)return parseFloat(a[1])},c=z.navigator.userAgent,
d,e,f,g,h;(d=z.opera&&z.opera.version&&parseInt(z.opera.version()))(h=b(c.match(Edge([^ ]+)$)))b(c.match(Chrome([^ ]+)))(e=b(c.match(Version([^ ]+) Safari)))(f=b(c.match(Firefox([^ ]+))))(g=a.a.Wb(c.match(MSIE ([^ ]+))))(g=b(c.match(rv([^ )]+))))}if(8=g&&10g)var m=a.a.g.Z(),l=a.a.g.Z(),k=function(b){var c=this.activeElement;(c=c&&a.a.g.get(c,l))&&c(b)},q=function(b,c){var d=b.ownerDocument;a.a.g.get(d,m)(a.a.g.set(d,m,!0),a.a.H(d,selectionchange,k));a.a.g.set(b,
l,c)};a.f.textInput={initfunction(b,c,l){function k(c,d){a.a.H(b,c,d)}function m(){var d=a.a.c(c());if(null===dd===p)d=;L!==p&&d===La.a.setTimeout(m,4)b.value!==d&&(x=!0,b.value=d,x=!1,v=b.value)}function t(){w(L=b.value,w=a.a.setTimeout(B,4))}function B(){clearTimeout(w);L=w=p;var d=b.value;v!==d&&(v=d,a.m.$a(c(),l,textInput,d))}var v=b.value,w,L,z=9==a.a.WtB,x=!1;g&&k(keypress,B);11g&&k(propertychange,function(a){xvalue!==a.propertyNamez(a)});8==g&&(k(keyup,B),k(keydown,
B));q&&(q(b,z),k(dragend,t));(!g9=g)&&k(input,z);5e&&textarea===a.a.P(b)(k(keydown,t),k(paste,t),k(cut,t))11dk(keydown,t)4f(k(DOMAutoComplete,B),k(dragdrop,B),k(drop,B))h&&number===b.type&&k(keydown,t);k(change,B);k(blur,B);a.o(m,null,{lb})}};a.m.va.textInput=!0;a.f.textinput={preprocessfunction(a,b,c){c(textInput,a)}}})();a.f.uniqueName={initfunction(b,c){if(c()){var d=ko_unique_+ ++a.f.uniqueName.qd;a.a.Xc(b,d)}}};a.f.uniqueName.qd=0;a.f.using={initfunction(b,
c,d,e,f){var g;d.has(as)&&(g={asd.get(as),noChildContextd.get(noChildContext)});c=f.createChildContext(c,g);a.Pa(c,b);return{controlsDescendantBindings!0}}};a.h.ea.using=!0;a.f.value={after[options,foreach],initfunction(b,c,d){var e=a.a.P(b),f=input==e;if(!fcheckbox!=b.type&&radio!=b.type){var g=[change],h=d.get(valueUpdate),m=!1,l=null;h&&(string==typeof h&&(h=[h]),a.a.gb(g,h),g=a.a.vc(g));var k=function(){l=null;m=!1;var e=c(),f=a.u.L(b);a.m.$a(e,d,value,f)};!a.a.W
!ftext!=b.typeoff==b.autocompleteb.form&&off==b.form.autocomplete-1!=a.a.A(g,propertychange)(a.a.H(b,propertychange,function(){m=!0}),a.a.H(b,focus,function(){m=!1}),a.a.H(b,blur,function(){m&&k()}));a.a.C(g,function(c){var d=k;a.a.Td(c,after)&&(d=function(){l=a.u.L(b);a.a.setTimeout(k,0)},c=c.substring(5));a.a.H(b,c,d)});var q;q=f&&file==b.typefunction(){var d=a.a.c(c());null===dd===p===db.value=a.v.K(k)}function(){var f=a.a.c(c()),g=a.u.L(b);if(null!==l&&
f===l)a.a.setTimeout(q,0);else if(f!==gg===p)select===e(g=d.get(valueAllowUnset),a.u.ya(b,f,g),gf===a.u.L(b)a.v.K(k))a.u.ya(b,f)};a.o(q,null,{lb})}else a.eb(b,{checkedValuec})},updatefunction(){}};a.m.va.value=!0;a.f.visible={updatefunction(b,c){var d=a.a.c(c()),e=none!=b.style.display;d&&!eb.style.display=!d&&e&&(b.style.display=none)}};a.f.hidden={updatefunction(b,c){a.f.visible.update(b,function(){return!a.a.c(c())})}};(function(b){a.f[b]={initfunction(c,d,e,f,g){return a.f.event.init.call(this,
c,function(){var a={};a[b]=d();return a},e,f,g)}}})(click);a.ca=function(){};a.ca.prototype.renderTemplateSource=function(){throw Error(Override renderTemplateSource);};a.ca.prototype.createJavaScriptEvaluatorBlock=function(){throw Error(Override createJavaScriptEvaluatorBlock);};a.ca.prototype.makeTemplateSource=function(b,c){if(string==typeof b){c=cw;var d=c.getElementById(b);if(!d)throw Error(Cannot find template with ID +b);return new a.B.D(d)}if(1==b.nodeType8==b.nodeType)return new a.B.ia(b);
throw Error(Unknown template type +b);};a.ca.prototype.renderTemplate=function(a,c,d,e){a=this.makeTemplateSource(a,e);return this.renderTemplateSource(a,c,d,e)};a.ca.prototype.isTemplateRewritten=function(a,c){return!1===this.allowTemplateRewriting!0this.makeTemplateSource(a,c).data(isRewritten)};a.ca.prototype.rewriteTemplate=function(a,c,d){a=this.makeTemplateSource(a,d);c=c(a.text());a.text(c);a.data(isRewritten,!0)};a.b(templateEngine,a.ca);a.ic=function(){function b(b,c,d,h){b=a.m.Zb(b);
for(var m=a.m.Ra,l=0;lb.length;l++){var k=b[l].key;if(Object.prototype.hasOwnProperty.call(m,k)){var q=m[k];if(function===typeof q){if(k=q(b[l].value))throw Error(k);}else if(!q)throw Error(This template engine does not support the '+k+' binding within its templates);}}d=ko.__tr_ambtns(function($context,$element){return(function(){return{ +a.m.ub(b,{valueAccessors!0})+ } })()},'+d.toLowerCase()+');return h.createJavaScriptEvaluatorBlock(d)+c}var c=(([a-z]+d)(s+(!data-binds=s)[a-z0-9-]+(=([^]'[^']'[^])))s+)data-binds=s(['])([sS])3gi,
d=x3c!--skobs([sS])s--x3eg;return{wdfunction(b,c,d){c.isTemplateRewritten(b,d)c.rewriteTemplate(b,function(b){return a.ic.Kd(b,c)},d)},Kdfunction(a,f){return a.replace(c,function(a,c,d,e,k){return b(k,c,d,f)}).replace(d,function(a,c){return b(c,x3c!-- ko --x3e,#comment,f)})},ldfunction(b,c){return a.aa.Wb(function(d,h){var m=d.nextSibling;m&&m.nodeName.toLowerCase()===c&&a.eb(m,b,h)})}}}();a.b(__tr_ambtns,a.ic.ld);(function(){a.B={};a.B.D=function(b){if(this.D=b){var c=
a.a.P(b);this.Db=script===c1textarea===c2template==c&&b.content&&11===b.content.nodeType34}};a.B.D.prototype.text=function(){var b=1===this.Dbtext2===this.DbvalueinnerHTML;if(0==arguments.length)return this.D[b];var c=arguments[0];innerHTML===ba.a.dc(this.D,c)this.D[b]=c};var b=a.a.g.Z()+_;a.B.D.prototype.data=function(c){if(1===arguments.length)return a.a.g.get(this.D,b+c);a.a.g.set(this.D,b+c,arguments[1])};var c=a.a.g.Z();a.B.D.prototype.nodes=function(){var b=this.D;
if(0==arguments.length){var e=a.a.g.get(b,c){},f=e.jb(3===this.Dbb.content4===this.Dbbp);if(!fe.hd)if(e=this.text())f=a.a.Ld(e,b.ownerDocument),this.text(),a.a.g.set(b,c,{jbf,hd!0});return f}a.a.g.set(b,c,{jbarguments[0]})};a.B.ia=function(a){this.D=a};a.B.ia.prototype=new a.B.D;a.B.ia.prototype.constructor=a.B.ia;a.B.ia.prototype.text=function(){if(0==arguments.length){var b=a.a.g.get(this.D,c){};b.jc===p&&b.jb&&(b.jc=b.jb.innerHTML);return b.jc}a.a.g.set(this.D,c,{jcarguments[0]})};
a.b(templateSources,a.B);a.b(templateSources.domElement,a.B.D);a.b(templateSources.anonymousTemplate,a.B.ia)})();(function(){function b(b,c,d){var e;for(c=a.h.nextSibling(c);b&&(e=b)!==c;)b=a.h.nextSibling(e),d(e,b)}function c(c,d){if(c.length){var e=c[0],f=c[c.length-1],g=e.parentNode,h=a.ga.instance,m=h.preprocessNode;if(m){b(e,f,function(a,b){var c=a.previousSibling,d=m.call(h,a);d&&(a===e&&(e=d[0]b),a===f&&(f=d[d.length-1]c))});c.length=0;if(!e)return;e===fc.push(e)(c.push(e,f),a.a.Ua(c,
g))}b(e,f,function(b){1!==b.nodeType&&8!==b.nodeTypea.uc(d,b)});b(e,f,function(b){1!==b.nodeType&&8!==b.nodeTypea.aa.bd(b,[d])});a.a.Ua(c,g)}}function d(a){return a.nodeTypea0a.lengtha[0]null}function e(b,e,f,h,m){m=m{};var p=(b&&d(b)f{}).ownerDocument,A=m.templateEngineg;a.ic.wd(f,A,p);f=A.renderTemplate(f,h,m,p);if(number!=typeof f.length0f.length&&number!=typeof f[0].nodeType)throw Error(Template engine must return an array of DOM nodes);p=!1;switch(e){case replaceChildrena.h.ua(b,
f);p=!0;break;case replaceNodea.a.Wc(b,f);p=!0;break;case ignoreTargetNodebreak;defaultthrow Error(Unknown renderMode +e);}p&&(c(f,h),m.afterRender&&a.v.K(m.afterRender,null,[f,h[m.as$data]]),replaceChildren==e&&a.j.Ga(b,a.j.T));return f}function f(b,c,d){return a.N(b)b()function===typeof bb(c,d)b}var g;a.ec=function(b){if(b!=p&&!(b instanceof a.ca))throw Error(templateEngine must inherit from ko.templateEngine);g=b};a.bc=function(b,c,h,m,r){h=h{};if((h.templateEngineg)==
p)throw Error(Set a template engine before calling renderTemplate);r=rreplaceChildren;if(m){var y=d(m);return a.$(function(){var g=c&&c instanceof a.facnew a.fa(c,null,null,null,{exportDependencies!0}),p=f(b,g.$data,g),g=e(m,r,p,g,h);replaceNode==r&&(m=g,y=d(m))},null,{Safunction(){return!y!a.a.Rb(y)},ly&&replaceNode==ry.parentNodey})}return a.aa.Wb(function(d){a.bc(b,c,h,d,replaceNode)})};a.Pd=function(b,d,g,h,m){function y(b,c){a.v.K(a.a.cc,null,[h,b,u,g,t,c]);a.j.Ga(h,a.j.T)}
function t(a,b){c(b,v);g.afterRender&&g.afterRender(b,a);v=null}function u(a,c){v=m.createChildContext(a,{asB,noChildContextg.noChildContext,extendfunction(a){a.$index=c;B&&(a[B+Index]=c)}});var d=f(b,a,v);return e(h,ignoreTargetNode,d,v,g)}var v,B=g.as,w=!1===g.includeDestroyeda.options.foreachHidesDestroyed&&!g.includeDestroyed;if(wg.beforeRemove!a.Oc(d))return a.$(function(){var b=a.a.c(d)[];undefined==typeof b.length&&(b=[b]);w&&(b=a.a.fb(b,function(b){return b===pnull===b
!a.a.c(b._destroy)}));y(b)},null,{lh});y(d.w());var z=d.subscribe(function(a){y(d(),a)},null,arrayChange);z.l(h);return z};var h=a.a.g.Z(),m=a.a.g.Z();a.f.template={initfunction(b,c){var d=a.a.c(c());if(string==typeof dd.name)a.h.Ea(b);else if(nodesin d){d=d.nodes[];if(a.N(d))throw Error('The nodes option must be a plain, non-observable array.');var e=d[0]&&d[0].parentNode;e&&a.a.g.get(e,m)(e=a.a.Xb(d),a.a.g.set(e,m,!0));(new a.B.ia(b)).nodes(e)}else if(d=a.h.childNodes(b),0d.length)e=
a.a.Xb(d),(new a.B.ia(b)).nodes(e);else throw Error(Anonymous template defined, but no template content was provided);return{controlsDescendantBindings!0}},updatefunction(b,c,d,e,f){var g=c();c=a.a.c(g);d=!0;e=null;string==typeof cc={}(g=c.name,ifin c&&(d=a.a.c(c[if])),d&&ifnotin c&&(d=!a.a.c(c.ifnot)));foreachin ce=a.Pd(gb,d&&c.foreach[],c,b,f)d(d=f,datain c&&(d=f.createChildContext(c.data,{asc.as,noChildContextc.noChildContext,exportDependencies!0})),e=a.bc(gb,d,c,
b))a.h.Ea(b);f=e;(c=a.a.g.get(b,h))&&function==typeof c.s&&c.s();a.a.g.set(b,h,!ff.ja&&!f.ja()pf)}};a.m.Ra.template=function(b){b=a.m.Zb(b);return 1==b.length&&b[0].unknowna.m.Hd(b,name)nullThis template engine does not support anonymous templates nested within its templates};a.h.ea.template=!0})();a.b(setTemplateEngine,a.ec);a.b(renderTemplate,a.bc);a.a.Jc=function(a,c,d){if(a.length&&c.length){var e,f,g,h,m;for(e=f=0;(!ded)&&(h=a[f]);++f){for(g=0;m=c[g];++g)if(h.value===m.value){h.moved=
m.index;m.moved=h.index;c.splice(g,1);e=g=0;break}e+=g}}};a.a.Ob=function(){function b(b,d,e,f,g){var h=Math.min,m=Math.max,l=[],k,p=b.length,n,r=d.length,t=r-p1,A=p+r+1,u,v,w;for(k=0;k=p;k++)for(v=u,l.push(u=[]),w=h(r,k+t),n=m(0,k-1);n=w;n++)u[n]=nkb[k-1]===d[n-1]v[n-1]h(v[n]A,u[n-1]A)+1n+1k+1;h=[];m=[];t=[];k=p;for(n=r;kn;)r=l[k][n]-1,n&&r===l[k][n-1]m.push(h[h.length]={statuse,valued[--n],indexn})k&&r===l[k-1][n]t.push(h[h.length]={statusf,valueb[--k],indexk})(--n,--k,
g.sparseh.push({statusretained,valued[n]}));a.a.Jc(t,m,!g.dontLimitMoves&&10p);return h.reverse()}return function(a,d,e){e=boolean===typeof e{dontLimitMovese}e{};a=a[];d=d[];return a.lengthd.lengthb(a,d,added,deleted,e)b(d,a,deleted,added,e)}}();a.b(utils.compareArrays,a.a.Ob);(function(){function b(b,c,d,h,m){var l=[],k=a.$(function(){var k=c(d,m,a.a.Ua(l,b))[];0l.length&&(a.a.Wc(l,k),h&&a.v.K(h,null,[d,k,m]));l.length=0;a.a.gb(l,k)},null,{lb,Safunction(){return!a.a.jd(l)}});
return{Yl,$k.ja()kp}}var c=a.a.g.Z(),d=a.a.g.Z();a.a.cc=function(e,f,g,h,m,l){function k(b){x={Aab,nba.sa(w++)};v.push(x);tF.push(x)}function q(b){x=r[b];w!==x.nb.w()&&D.push(x);x.nb(w++);a.a.Ua(x.Y,e);v.push(x)}function n(b,c){if(b)for(var d=0,e=c.length;de;d++)a.a.C(c[d].Y,function(a){b(a,d,c[d].Aa)})}f=f[];undefined==typeof f.length&&(f=[f]);h=h{};var r=a.a.g.get(e,c),t=!r,v=[],u=0,w=0,B=[],z=[],C=[],D=[],F=[],x,I=0;if(t)a.a.C(f,k);else{if(!lr&&r._countWaitingForRemove){var E=
a.a.Mb(r,function(a){return a.Aa});l=a.a.Ob(E,f,{dontLimitMovesh.dontLimitMoves,sparse!0})}for(var E=0,G,H,K;G=l[E];E++)switch(H=G.moved,K=G.index,G.status){case deletedfor(;uK;)q(u++);H===p&&(x=r[u],x.$&&(x.$.s(),x.$=p),a.a.Ua(x.Y,e).length&&(h.beforeRemove&&(v.push(x),I++,x.Aa===dx=nullC.push(x)),x&&B.push.apply(B,x.Y)));u++;break;case addedfor(;wK;)q(u++);H!==p(z.push(v.length),q(H))k(G.value)}for(;wf.length;)q(u++);v._countWaitingForRemove=I}a.a.g.set(e,c,v);n(h.beforeMove,D);a.a.C(B,
h.beforeRemovea.naa.removeNode);var M,O,P;try{P=e.ownerDocument.activeElement}catch(N){}if(z.length)for(;(E=z.shift())!=p;){x=v[E];for(M=p;E;)if((O=v[--E].Y)&&O.length){M=O[O.length-1];break}for(f=0;u=x.Y[f];M=u,f++)a.h.Vb(e,u,M)}E=0;for(z=a.h.firstChild(e);x=v[E];E++){x.Ya.a.extend(x,b(e,g,x.Aa,m,x.nb));for(f=0;u=x.Y[f];z=u.nextSibling,M=u,f++)u!==z&&a.h.Vb(e,u,M);!x.Dd&&m&&(m(x.Aa,x.Y,x.nb),x.Dd=!0,M=x.Y[x.Y.length-1])}P&&e.ownerDocument.activeElement!=P&&P.focus();n(h.beforeRemove,C);for(E=
0;EC.length;++E)C[E].Aa=d;n(h.afterMove,D);n(h.afterAdd,F)}})();a.b(utils.setDomNodeChildrenFromArrayMapping,a.a.cc);a.ba=function(){this.allowTemplateRewriting=!1};a.ba.prototype=new a.ca;a.ba.prototype.constructor=a.ba;a.ba.prototype.renderTemplateSource=function(b,c,d,e){if(c=(9a.a.W0b.nodes)b.nodes()null)return a.a.la(c.cloneNode(!0).childNodes);b=b.text();return a.a.ta(b,e)};a.ba.Na=new a.ba;a.ec(a.ba.Na);a.b(nativeTemplateEngine,a.ba);(function(){a.Za=function(){var a=this.Gd=function(){if(!v
!v.tmpl)return 0;try{if(0=v.tmpl.tag.tmpl.open.toString().indexOf(__))return 2}catch(a){}return 1}();this.renderTemplateSource=function(b,e,f,g){g=gw;f=f{};if(2a)throw Error(Your version of jQuery.tmpl is too old. Please upgrade to jQuery.tmpl 1.0.0pre or later.);var h=b.data(precompiled);h(h=b.text(),h=v.template(null,{{ko_with $item.koBindingContext}}+h+{{ko_with}}),b.data(precompiled,h));b=[e.$data];e=v.extend({koBindingContexte},f.templateOptions);e=v.tmpl(h,b,e);e.appendTo(g.createElement(div));
v.fragments={};return e};this.createJavaScriptEvaluatorBlock=function(a){return{{ko_code ((function() { return +a+ })()) }}};this.addTemplate=function(a,b){w.write(script type='texthtml' id='+a+'+b+x3cscript)};0a&&(v.tmpl.tag.ko_code={open__.push($1  '');},v.tmpl.tag.ko_with={openwith($1) {,close} })};a.Za.prototype=new a.ca;a.Za.prototype.constructor=a.Za;var b=new a.Za;0b.Gd&&a.ec(b);a.b(jqueryTmplTemplateEngine,a.Za)})()})})();})();